version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: my_database
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_db
    ports:
      - "3306:3306"
